# ---------- Stage 1: Builder ----------
FROM python:3.13-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY . .


# ---------- Stage 2: Runner ----------
FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app


EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/', timeout=2)" || exit 1

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mysite.wsgi:application"]

